build:
    dependencies:
        before:
            - 'source <(curl -fsSL https://raw.githubusercontent.com/phayes/go-scrutinize/master/install-golang)'

    tests:
        override:
            -
                command: 'cd $PROJECTPATH && go-scrutinize'
                idle_timeout: 600
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
                analysis:
                    file: 'checkstyle_report.xml'
                    format: 'general-checkstyle'
